spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: budget-monolith
              uri: http://monolith:8080
              predicates:
                - Path=/api/**
            - id: static
              uri: http://monolith:8080
              predicates:
                - Path=/**, /index.html, /css/**, /js/**, /favicon.ico

server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

app:
  auth-service:
    url: http://monolith:8080
  internal:
    token: ${INTERNAL_TOKEN}
